---
title: "Clothing Images"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r}

install.package(dplyr)
install.package(imager)
setwd()
library(reticulate) #package to access python libraries
use_python("C:/Windows/py.exe", required = T)




library(dplyr)
labels <- read.csv("../data/styles.csv",
                     header= T) %>%
  unique(.)

#subset to 10,000 images. indexes are already random
labels <- labels[1:10000,]

images <- list.files("../data/images")
images  <- gsub(".jpg", "",images)
images <- images[images %in% labels$id]
#number of images is 9995. there are some photos not in label sheet

#get true labels
labels <- labels[labels$id %in% images,]

#get image paths again
images <- paste0("../data/images/",images, ".jpg")

library(imager)
photos <- lapply(images, load.image)
dim(photos[[1]]) #3 channels RGB #60h 80w 1d 3channels

summary(photos[[50]]) #not 8 bit pixelated, scale is 0 to 1


photos[[1]]
plot(photos[[1]])
plot(photos[[23]])

```


```{r label distribution}
summary(labels)

nas <- filter(labels, is.na(labels$baseColour)) #2

labels$baseColour[labels$id=="11293"] = "Blue" #visual imputation
labels$baseColour[labels$id=="41347"] = "Red"

target_dist <- table(subset(labels,select=c(baseColour)))
#uneven distribution of colors
target_dist

#group up colors with less than 10 counts
labels$baseColour <- gsub("Lime Green", "Green", labels$baseColour) #only 1 sample
labels$baseColour <- gsub("Mushroom Brown", "Brown", labels$baseColour) #only 6 samples
labels$baseColour <- gsub("Taupe", "Brown", labels$baseColour) #only 3 samples
labels$baseColour <- gsub("Coffee Brown", "Brown", labels$baseColour) #only 9 samples
labels$baseColour <- gsub("Rose", "Pink", labels$baseColour) #only 7 samples
labels$baseColour <- gsub("Mauve", "Purple", labels$baseColour) #only 9 samples
labels$baseColour <- gsub("Nude", "Brown", labels$baseColour) #only 4 samples
labels$baseColour <- gsub("Sea Green", "Green", labels$baseColour) #only 8 samples

target_dist <- table(subset(labels,select=c(baseColour)))


tab <- datalabels1tab <- data.frame(target_dist)
library(ggplot2)
target_plot <- ggplot(tab, aes(x= baseColour, y= Freq))+
  geom_col()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 0.5))+
  labs(title= "Target Color Label Distribution")
library(plotly)
ggplotly(target_plot)

table(subset(labels,select=c(gender))) #mostly women and men clothing
table(subset(labels,select=c(usage))) #mostly casual clothing


```

```{r data augmentation}
n_samples <- nrow(labels) #9995 photos
n_categories <- NROW(unique(labels$baseColour)) #37 colors

#weights to match up to majority class, majority class has lowest weight
weights <- n_samples / (n_samples * tab$Freq) #outputs weights for each class

#make a list for keras
class_weights <- vector()
for (i in 1:length(weights)) {
  class_index <- as.character(i - 1)
  #print(class_index)
  # Assign the weight to that specific class index
  class_weights[[class_index]] <- weights[i]
}

```

```{r data split}

training_limit <- round(nrow(labels) * 0.75) #7496
training_limit
training_photos <- photos[1:training_limit]

test_limit <- round(nrow(labels) * 0.25/2)
test_photos <- photos[(training_limit+1): (training_limit+test_limit)]

validation_photos <- photos[((training_limit+test_limit)+1):
                              (nrow(labels))]
image_id_order <- gsub("../data/images/","",images)
image_id_order <- gsub(".jpg","",image_id_order)

labels_by_id_order <-labels %>%
  filter(id %in% image_id_order) %>% #so matchup is not rowwise
  select(id, baseColour) %>%
  arrange(match(id, image_id_order))

training_labels <- labels_by_id_order[1:training_limit,]
test_labels <- labels_by_id_order[(training_limit+1): (training_limit+test_limit),]
validation_labels <- labels_by_id_order[((training_limit+test_limit)+1):
                              (nrow(labels)),]




```


```{r check splits}

table(training_labels$baseColour)
NROW(unique(training_labels$baseColour)) #37

table(test_labels$baseColour)
NROW(unique(test_labels$baseColour)) #36

table(validation_labels$baseColour)
NROW(unique(validation_labels$baseColour)) #36


```

```{r redo partitioning}

library(caret)

set.seed(123)
train_indices <- createDataPartition(labels_by_id_order$baseColour,
                                     p = 0.75, list = FALSE)

train_labels <- labels_by_id_order[train_indices, ] #visually checked that labels match
train_photos <- photos[train_indices]

remain_labels <- labels_by_id_order[-train_indices,]
remain_photos <- photos[-train_indices]

remain_indices <- createDataPartition(remain_labels$baseColour,
                                     p = 0.50, list = FALSE)

test_labels <- remain_labels[remain_indices,]
test_photos <- remain_photos[remain_indices]

validation_labels <- remain_labels[-remain_indices,]
validation_photos <- remain_photos[-remain_indices]


```

```{r check splits again}


table(train_labels$baseColour)
NROW(unique(train_labels$baseColour)) #37

table(test_labels$baseColour)
NROW(unique(test_labels$baseColour)) #37

table(validation_labels$baseColour)
NROW(unique(validation_labels$baseColour)) #37

```

```{r color label encoding}

#ml may not understand text
one_hot_encode <- function(labels, num_classes) {
  # Create a matrix of zeros
  encoded_labels <- matrix(0, nrow = length(labels), ncol = num_classes)
  
  # Set the appropriate index to 1 for each label
  for (i in seq_along(labels)) {
    encoded_labels[i, labels[i] + 1] <- 1
  }
  return(encoded_labels)
}

all_colors <- unique(labels$baseColour) 
train_colors <- factor(train_labels$baseColour, levels = all_colors)
train_numeric <- as.integer(train_colors) - 1
train_y <- one_hot_encode(train_numeric, 37)

valid_colors <- factor(validation_labels$baseColour, levels = all_colors)
valid_numeric <- as.integer(valid_colors) - 1
valid_y       <- one_hot_encode(valid_numeric, 37)


test_colors <- factor(test_labels$baseColour, levels = all_colors)
test_numeric <- as.integer(test_colors) - 1
test_y       <- one_hot_encode(test_numeric, 37)



```


```{r modeling}

#reticulate::virtualenv_remove("r-tensorflow")
#reticulate::install_python(version = "3.10") #specific version for keras3
#keras3::install_keras(version = "3.10")
# library(reticulate) #package to access python libraries
# use_python("C:/Windows/py.exe", required = T)
# library(tensorflow)
library(keras3)
#keras3::install_keras()

library(mlflow)


transfer_model <- application_resnet50_v2(
  weights = 'imagenet', # Load weights pre-trained on ImageNet.
  input_shape = c(60, 80, 3),
  include_top = FALSE # Do not include the ImageNet classifier at the top.
)


#change up the photos
data_augmentation <- keras_model_sequential(
  layers=list(
        layer_input(shape = c(60L, 80L,3)) ,
        layer_random_flip(mode = "horizontal") ,
        layer_random_rotation(factor = 0.125,# rotation_range = 45 
                              fill_mode = "constant",
                              fill_value = 1.0) , #white background in images
        layer_random_translation(height_factor = 0.1,
                                 width_factor = 0.1,
                                 fill_mode = "constant",
                              fill_value = 1.0) ,
        layer_random_zoom(height_factor = 0.15, width_factor = 0.15,
                          fill_mode = "constant",
                              fill_value = 1.0)))

#could log data augmentation
#no more training for transfer model
transfer_model$trainable <- FALSE

inputs <- layer_input(shape = c(60, 80, 3))

output <- inputs %>%
  data_augmentation() %>%
    transfer_model(training = FALSE) %>%
  layer_global_average_pooling_2d() %>% #takes in everything in comparison to max that looks for peaks
  layer_dropout(.4) %>%                 #drop 40% of nodes
  layer_dense(units= 37, activation = "softmax")
  
 model <- keras_model(inputs= inputs, outputs = output) 
summary(model)


```


```{r model setup}

set.seed(425)
#hyperparameters
model %>% compile(optimizer = optimizer_adam(learning_rate = 0.001),
                  loss = 'categorical_crossentropy',
                  metrics = list(
                    metric_categorical_accuracy(), 
                    metric_precision(), 
                    metric_recall(), 
                    metric_f1_score(average = "macro")) #to see score per class
)

```


```{r make photo array}
# 1. Define standard operational targets
img_height <- 60
img_width  <- 80
channels   <- 3

# 2. Re-engineered keras3 compatible function
process_and_resize <- function(img, index) {
  img_dims <- dim(img)
  
  # Step A: Explicitly handle the 60x80x1x3 structure safely
  if (length(img_dims) == 4) {
    slice <- array(0, dim = c(img_dims[1], img_dims[2], img_dims[4]))
    for(c in 1:img_dims[4]) {
      slice[, , c] <- img[, , 1, c]
    }
  } else {
    slice <- img
  }
  
  slice_dims <- dim(slice)
  
  # Step B: Get the underlying Python utils module from Keras
  # This bypasses R's namespace export issues completely
  py_keras_utils <- reticulate::import("keras.utils")
  
  # Step C: If grayscale (2D matrix), upgrade it to 3D
  if (length(slice_dims) == 2) {
    slice <- array(slice, dim = c(slice_dims[1], slice_dims[2], 1))
    slice_dims <- dim(slice)
  }
  
  # Step D: If spatial dimensions mismatch, use Keras backend Python utilities
  if (slice_dims[1] != img_height || slice_dims[2] != img_width) {
    # Convert matrix array to PIL image instance using Python backend
    py_img <- py_keras_utils$array_to_img(slice)
    # Resize utilizing Python's native toolset
    py_img_resized <- py_img$resize(c(as.integer(img_width), as.integer(img_height)))
    # Convert back to clean array matrix
    resized_array <- py_keras_utils$img_to_array(py_img_resized)
    return(resized_array)
  }
  
  return(slice)
}


# Process Training Set
num_train <- length(train_photos)
train_photos_array <- array(0, dim = c(num_train, img_height, img_width, channels))

for(i in 1:num_train) {
  train_photos_array[i, , , ] <- process_and_resize(train_photos[[i]], i)
}

# Process Validation Set
num_valid <- length(validation_photos)
validation_photos_array <- array(0, dim = c(num_valid, img_height, img_width, channels))

for(i in 1:num_valid) {
  validation_photos_array[i, , , ] <- process_and_resize(validation_photos[[i]], i)
}

##test set
num_test <- length(test_photos)
test_photos_array <- array(0, dim = c(num_test, img_height, img_width, channels))

for(i in 1:num_test) {
  test_photos_array[i, , , ] <- process_and_resize(test_photos[[i]], i)
}

```


```{r model performance}

set.seed(123)
performance_measures <- model %>% fit(
                  train_photos_array, train_y,
                  batch_size = 60,
                  epochs = 25,
                  validation_data = list(validation_photos_array, valid_y),
                  class_weight = class_weights,
                  callbacks = list(
                      callback_early_stopping(
                        monitor = 'val_loss',
                        patience = 4,
                        restore_best_weights = T)),
                  verbose = 1 
)


```


```{r mlflow tracking}
library(reticulate)
py_install("mlflow", pip = TRUE) #ensure mlflow is installed in current python env
Sys.setenv(MLFLOW_PYTHON_BIN = reticulate::py_config()$python)


library(mlflow)
mlflow_py <- import("mlflow")

mlflow_py$set_experiment(experiment_name = "Transfer learning ResNetv50 model")

run <- mlflow_py$start_run()

  mlflow_py$log_param("backbone", "ResNet50v2")

  # Loop exactly 10 times over your existing arrays
  for (epoch in 1:10) {
    mlflow_py$log_metric("training_categorical_accuracy",
                performance_measures[["metrics"]][["categorical_accuracy"]][epoch],
                step = as.integer(epoch))
    mlflow_py$log_metric("training_loss", performance_measures[["metrics"]][["loss"]][epoch], step = as.integer(epoch))
  }

```


